Lyduke56/Project-Readr

project-readr/src/components/WelcomeNavbar.css
project-readr/src/pages/SignUp.jsx
project-readr/src/pages/WelcomePage.css
project-readr/src/pages/WelcomePage.jsx

[Feature][Longakit] Home Page

---

project-readr/src/components/WelcomeNavbar.css
project-readr/src/pages/WelcomePage.css

Finalized Welcome Page. Open to changes and modifications

[Feature][Bartolabac] Finalized Welcome Page

---

project-readr/src/components/HomepageNavbar.css
project-readr/src/components/HomepageNavbar.jsx

- Added the User's display name and profile image on the Home Navbar

[Feature][Longakit] Home Navbar

---

project-readr/src/pages/Home.css
project-readr/src/pages/Home.jsx

- Added Author Filtering
- Increase Default Display from 8 to 40
- Minor UI Fixes

[Feature][Rosal] - API Integration Home Page 1.2

---

project-readr/src/App.jsx
project-readr/src/Modal/Modal.css
project-readr/src/Modal/Modal.jsx
project-readr/src/Modal/forgotPass.css
project-readr/src/Modal/forgotPass.jsx
project-readr/src/context/AuthContext.jsx
project-readr/src/pages/AddInfo.jsx
project-readr/src/pages/ResetPass.jsx
project-readr/src/pages/SignIn.css
project-readr/src/pages/SignIn.jsx

-Added forgotPass page (jsx and css), UI need fix
-Added resetPass page (jsx and css), no UI for now -Added Modal (jsx,css) - for the popped up small page feature  thingy in forgot password 
-Made changes from signIn page

[Feature][Longakit] Forgot Password

---

project-readr/src/pages/Home.css
project-readr/src/pages/Home.jsx
project-readr/src/pages/Profile.css

[Feature][Bartolabac] UI Fixes for Home page

---

project-readr/src/pages/Author.jsx
project-readr/src/pages/Book.jsx

[Feature][Rosal] - API Integration Description

---

project-readr/src/context/AuthContext.jsx
project-readr/src/pages/Home.jsx
project-readr/src/pages/Profile.jsx
project-readr/src/pages/ReadingList.jsx

-added reading-list feature and binds into the database
-adjustments for profile.jsx, home.jsx. readinglist.jsx, and authcontext.jsx
- left with UI improvementx

[Feature][Longakit] Add Read List

---

project-readr/src/pages/Homepage.jsx
project-readr/src/pages/Profile.css
project-readr/src/pages/Profile.jsx

- UI fixed
- Added list of user's rated books

[Feature][Longakit] Profile Page

---

project-readr/src/components/HomepageNavbar.jsx
project-readr/src/pages/Book.jsx
project-readr/src/pages/Discover.css
project-readr/src/pages/Discover.jsx
project-readr/src/pages/Home.css
project-readr/src/pages/Home.jsx
project-readr/src/pages/Homepage.css
project-readr/src/pages/Homepage.jsx
project-readr/src/pages/ReadingList.css
project-readr/src/pages/ReadingList.jsx
project-readr/src/pages/SignIn.jsx
project-readr/src/pages/WelcomePage.css

Changed the UI organization and color scheme, added some designs

[Changes][Bartolabac] UI fixes and Re-routing

---

project-readr/src/pages/Book.css
project-readr/src/pages/Book.jsx
project-readr/src/pages/Homepage.css
project-readr/src/pages/Homepage.jsx

Fixed UI for Home.jsx and beautified it. Also fixed Book.jsx UI and rating functionality

[Changes][Bartolabac] UI Fix and Book Implementation fix

---

project-readr/src/App.jsx
project-readr/src/components/HomepageNavbar.jsx
project-readr/src/components/Layout.jsx
project-readr/src/pages/Author.css
project-readr/src/pages/Author.jsx
project-readr/src/pages/Genre.css
project-readr/src/pages/Genre.jsx

Author fixes and added a new genre page

[Feature][Ybanez] UI fixes and new genre page

---

project-readr/src/components/Stack.css
project-readr/src/components/Stack.jsx
project-readr/src/pages/Discover.jsx

rerouted the book cards in the discover books display so that when clicked will direct to the book page

[Changes][Bartolabac] Fixes

---

project-readr/src/App.jsx
project-readr/src/components/FriendRequestBell.css
project-readr/src/components/FriendRequestBell.jsx
project-readr/src/components/HomepageNavbar.css
project-readr/src/components/HomepageNavbar.jsx
project-readr/src/components/Layout.jsx
project-readr/src/pages/AddProfile.css
project-readr/src/pages/AddProfile.jsx
project-readr/src/pages/FriendList.jsx
project-readr/src/pages/Profile.css
project-readr/src/pages/Profile.jsx

- Add friend
- Pending request
- Search User
- Total User
- Bell notifications

[Feature][Longakit] Friends

---

project-readr/src/pages/Genre.jsx
project-readr/src/pages/Home.css
project-readr/src/pages/Home.jsx

• Added subjects filtering
• Added search details
• tweaked no search results
• Added subjects filtering on genre click

[Feature][Rosal] Searching Quality of Life

---

project-readr/src/pages/Book.css
project-readr/src/pages/Book.jsx
project-readr/src/pages/Genre.css
project-readr/src/pages/Home.css

fixed some ui and fonts since naguba nasad hUUUUU

[fixes][bartolabac] ficed uI

---

project-readr/src/pages/Book.jsx
project-readr/src/pages/Home.jsx

• force to top page on book description open
• better scrolling on search results
• on recommendation cards clicked, open new tab with book description

[Features][Rosal] - even more fixes

---

project-readr/src/pages/Home.css
project-readr/src/pages/Home.jsx

[Fixes][Bartolabac] UI changes

---

project-readr/package-lock.json
project-readr/package.json
project-readr/src/App.jsx
project-readr/src/components/FriendRequestBell.jsx
project-readr/src/components/Layout.jsx
project-readr/src/pages/Book.css
project-readr/src/pages/Book.jsx
project-readr/src/pages/FriendList.jsx
project-readr/src/pages/FriendProfile.jsx
project-readr/src/pages/Profile.css
project-readr/src/pages/Profile.jsx

- added friend list
- updates notif bell fature
- ui for click handling need fix

[Feature][Longakit] Friends List

---

project-readr/src/Modal/forgotPass.jsx
project-readr/src/components/FriendRequestBell.css
project-readr/src/components/HomepageNavbar.css
project-readr/src/components/HomepageNavbar.jsx
project-readr/src/pages/AddProfile.css
project-readr/src/pages/Book.css

added a home button on the nave bar and changes their colors. Also changed the color of Add Friend UI

[changes][bartolabac] Navbar changes, add friend UI changes
